# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ga-deploy]
  pull_request:
    branches: [ga-deploy]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      # Runs a single command using the runners shell
      - name: Init project
        run: npm i

      - name: Create .env file
        run: |
          touch .env
          echo SILEX_FRONT_URL="http://localhost:3000" >> .env
          echo ZOU_API_URL="http://localhost" >> .env
          echo PORT="5118" >> .env

      - name: Run test Mocha
        run: |
          npm run mocha
